from rest_framework import routers
from main.views import *

router = routers.DefaultRouter()

router.register("slider", SliderView)
router.register("logo", LogoView)
router.register("category", CategoryView)
router.register("news", NewsView)
router.register("malumotlar", MalumotlarView)
router.register("video", VideoView)
router.register("videonews", VideoNewsView)
router.register("xabarlar", XabarlarView)
router.register("reklama", ReklamaView)
router.register("foydalisaytlar", FoydaliSaytlarView)
router.register("andonorganing", AndOrganingView)
router.register("malumotlar2", Malumotlar2View)
router.register("tavsiyavideo", TavsiyaVideoView)
router.register("kerak", KerakView)
router.register("loyiha1", Loyiha1View)
router.register("xizmatlar", XizmatlarView)
router.register("andijon", AndijonView)
router.register("loyiha2", Loyiha2View)
router.register("invstarmoqlar", InvsTarmoqlarView)
router.register("hujjat", HujjatView)
router.register("qoshimchaxizmat", QoshimchaXizmatView)
router.register("savol", SavolView)
router.register("javob", JavobView)
router.register("loyiha3", Loyiha3View)
router.register("info", InfoView)
