# Generated by Django 3.2.9 on 2022-03-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hujjat',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
