# Generated by Django 3.2.9 on 2022-03-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_savol_javob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Savol_Javob',
        ),
    ]
